# Generated by Django 4.1.1 on 2023-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_user_blogpost_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
